# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/graph.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x11proto/graph.proto"M\n\x04Port\x12\x0b\n\x03uid\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x19\n\x0clast_updated\x18\x03 \x01(\x05H\x00\x88\x01\x01\x42\x0f\n\r_last_updated">\n\nConnection\x12\x18\n\tfrom_port\x18\x01 \x01(\x0b\x32\x05.Port\x12\x16\n\x07to_port\x18\x02 \x01(\x0b\x32\x05.Port"t\n\x04\x43\x65ll\x12\x0b\n\x03uid\x18\x01 \x01(\t\x12\x0c\n\x04\x63ode\x18\x02 \x01(\t\x12\x17\n\x08in_ports\x18\x04 \x03(\x0b\x32\x05.Port\x12\x18\n\tout_ports\x18\x05 \x03(\x0b\x32\x05.Port\x12\x13\n\x06output\x18\x06 \x01(\tH\x00\x88\x01\x01\x42\t\n\x07_output"\x82\x01\n\x05Graph\x12\x13\n\x04root\x18\x01 \x01(\x0b\x32\x05.Cell\x12\x14\n\x05\x63\x65lls\x18\x02 \x03(\x0b\x32\x05.Cell\x12 \n\x0b\x63onnections\x18\x03 \x03(\x0b\x32\x0b.Connection\x12\x1a\n\rselected_cell\x18\x04 \x01(\tH\x00\x88\x01\x01\x42\x10\n\x0e_selected_cellb\x06proto3'
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "proto.graph_pb2", globals())
if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    _PORT._serialized_start = 21
    _PORT._serialized_end = 98
    _CONNECTION._serialized_start = 100
    _CONNECTION._serialized_end = 162
    _CELL._serialized_start = 164
    _CELL._serialized_end = 280
    _GRAPH._serialized_start = 283
    _GRAPH._serialized_end = 413
# @@protoc_insertion_point(module_scope)
