repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: 8900e3ac8a8f610d4c1b3fbe7bdf4f0358efc28d
    hooks:
    -   id: black
# -   repo: https://github.com/pre-commit/mirrors-mypy
#     rev: 'v0.961'
#     hooks:
#     -   id: mypy
#         additional_dependencies: ['types-protobuf']
